// Generated by PMS #485
package identitycenter

import (
	"context"
	"strings"

	"github.com/hashicorp/go-multierror"
	"github.com/hashicorp/go-uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/tidwall/gjson"

	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/config"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/httphelper"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/helper/schemas"
	"github.com/huaweicloud/terraform-provider-huaweicloud/huaweicloud/utils"
)

func DataSourceIdentitycenterProvisionedPermissionSets() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceIdentitycenterProvisionedPermissionSetsRead,

		Schema: map[string]*schema.Schema{
			"region": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: `Specifies the region in which to query the resource. If omitted, the provider-level region will be used.`,
			},
			"instance_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the ID of an IAM Identity Center instance.`,
			},
			"permission_set_id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the ID of a permission set.`,
			},
			"target_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: `Specifies the account ID.`,
			},
			"target_type": {
				Type:        schema.TypeString,
				Required:    true,
				Description: `Specifies the type of the principal to be attached.`,
			},
			"permission_set_provisioning_status": {
				Type:        schema.TypeList,
				Computed:    true,
				Description: `The authorization details of a permission set.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"status": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The authorization status of a permission set.`,
						},
						"account_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The ID of a specified account.`,
						},
						"created_at": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The time when a permission set was created.`,
						},
						"failure_reason": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The failure reason.`,
						},
						"permission_set_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: `The ID of a permission set.`,
						},
					},
				},
			},
		},
	}
}

type ProvisionedPermissionSetsDSWrapper struct {
	*schemas.ResourceDataWrapper
	Config *config.Config
}

func newProvisionedPermissionSetsDSWrapper(d *schema.ResourceData, meta interface{}) *ProvisionedPermissionSetsDSWrapper {
	return &ProvisionedPermissionSetsDSWrapper{
		ResourceDataWrapper: schemas.NewSchemaWrapper(d),
		Config:              meta.(*config.Config),
	}
}

func dataSourceIdentitycenterProvisionedPermissionSetsRead(_ context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	wrapper := newProvisionedPermissionSetsDSWrapper(d, meta)
	proPerSetRst, err := wrapper.ProvisionPermissionSet()
	if err != nil {
		return diag.FromErr(err)
	}

	id, err := uuid.GenerateUUID()
	if err != nil {
		return diag.FromErr(err)
	}
	d.SetId(id)

	err = wrapper.provisionPermissionSetToSchema(proPerSetRst)
	if err != nil {
		return diag.FromErr(err)
	}

	return nil
}

// @API IDENTITYCENTER POST /v1/instances/{instance_id}/permission-sets/{permission_set_id}/provision
func (w *ProvisionedPermissionSetsDSWrapper) ProvisionPermissionSet() (*gjson.Result, error) {
	client, err := w.NewClient(w.Config, "identitycenter")
	if err != nil {
		return nil, err
	}

	uri := "/v1/instances/{instance_id}/permission-sets/{permission_set_id}/provision"
	uri = strings.ReplaceAll(uri, "{instance_id}", w.Get("instance_id").(string))
	uri = strings.ReplaceAll(uri, "{permission_set_id}", w.Get("permission_set_id").(string))
	params := map[string]any{
		"target_id":   w.Get("target_id"),
		"target_type": w.Get("target_type"),
	}
	params = utils.RemoveNil(params)
	return httphelper.New(client).
		Method("POST").
		URI(uri).
		Body(params).
		Request().
		Result()
}

func (w *ProvisionedPermissionSetsDSWrapper) provisionPermissionSetToSchema(body *gjson.Result) error {
	d := w.ResourceData
	mErr := multierror.Append(nil,
		d.Set("region", w.Config.GetRegion(w.ResourceData)),
		d.Set("permission_set_provisioning_status", schemas.ObjectToList(body.Get("permission_set_provisioning_status"),
			func(perSetProStatus gjson.Result) any {
				return map[string]any{
					"status":            perSetProStatus.Get("status").Value(),
					"account_id":        perSetProStatus.Get("account_id").Value(),
					"created_at":        perSetProStatus.Get("created_date").Value(),
					"failure_reason":    perSetProStatus.Get("failure_reason").Value(),
					"permission_set_id": perSetProStatus.Get("permission_set_id").Value(),
				}
			},
		)),
	)
	return mErr.ErrorOrNil()
}
